[package]
name = "app_therapy"
version = "0.1.0"
authors = ["leakybucket <DamnBigMan@gmail.com>"]

[dependencies]
postgres = "*"

# config parsing
serde = "*"
serde_json = "*"
serde_derive = "*"

# message encryption
sodiumoxide = "*"

# For arg stuff
docopt = "*"
rustc-serialize = "*"
